# default false (klipper-lb)
disable_service_lb: true

# default false
install_rook: true

# default true. make sure install_rook is true
create_block_storage: true
create_shared_filesystem: true

# default false
install_kustomize: true
kustomize_install_dir: /root

# install metallb. default false
install_metallb: true
metallb_version: v0.13.12
metallb_kustomize_dir: /root/metallb_kustomize
metallb_address_range: 192.168.126.50-192.168.126.80
