# default false (klipper-lb)
disable_service_lb: true

# default false
install_rook: false

# default true. make sure install_rook is true
create_block_storage: true
create_shared_filesystem: true

# install metallb. default false
install_metallb: true
metallb_version: v0.13.12
metallb_kustomize_dir: /root/metallb_kustomize
metallb_address_range: 192.168.126.50-192.168.126.80

# install awx. default false
install_awx: false
awx_version: 2.8.0
awx_kustomize_dir: /root/awx_kustomize

# install gitea
install_gitea: false
storageclass: local-path
gitea_http_nodport: 30000
gitea_ssh_nodport: 30001

# docker distribution(container private registry)
install_docker_distribution: true
private_key_path: /root/docker_registry_private.key
cert_pem_path: /root/docker_registry_certificate.pem
secret_name_docker_registry: registry-secret
pvc_name_docker_registry: pvc-registry
docker_registry_stoage_class_name: local-path
docekr_registry_storage_size: 5Gi
docker_registry_pvc_yaml_path: /root/docker_registry_pvc.yaml
htpasswd_file_path: /root/htpasswd
basic_auth_user:
- user: "admin"
  pass: "admin"
- user: "test01"
  pass: "test01"