# default false (klipper-lb)
disable_service_lb: true

# default false
install_rook: false

# default true. make sure install_rook is true
create_block_storage: true
create_shared_filesystem: true

# install metallb. default false
install_metallb: true
metallb_version: v0.13.12
metallb_kustomize_dir: /root/metallb_kustomize
metallb_address_range: 192.168.126.50-192.168.126.80

# install awx. default false
install_awx: false
awx_version: 2.8.0
awx_kustomize_dir: /root/awx_kustomize

# install gitea
install_gitea: true
storageclass: local-path
gitea_http_nodport: 30000
gitea_ssh_nodport: 30001
