- name: ensure httpd-tools is installed
  ansible.builtin.dnf:
    name: httpd-tools
    state: present
  
- name: update basic authentication file
  ansible.builtin.command:
    cmd: "htpasswd -Bbc {{ htpasswd_file_path }} {{ item.user }} {{ item.pass }}"
  loop: "{{ basic_auth_user }}"