- name: ensure httpd-tools is installed
  ansible.builtin.dnf:
    name: httpd-tools
    state: present
  
- name: update basic authentication file
  ansible.builtin.command:
    cmd: "htpasswd -Bb {{ htpasswd_file_path }} {{ item.user }} {{ item.pass }}"
  loop: "{{ basic_auth_user }}"

- name: check if a secret {{ secret_name_docker_registry }} exists
  ansible.builtin.shell:
    cmd: "kubectl get secrets -n default |grep -c {{ secret_name_htpasswd }}"
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: secret_out

- name: create secret for htpasswd
  ansible.builtin.command:
    cmd: "kubectl create secret generic {{ secret_name_htpasswd }} --from-file={{ htpasswd_file_path }}" 
  environment: 
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: "secret_out.stdout|int == 0"