---
- hosts: k3s
  gather_facts: false
  tasks:
  - name: install k3s
    ansible.builtin.import_role:
      name: install_k3s 

  - name: install k3s
    ansible.builtin.import_role:
      name: install_rook
    when: install_rook

  - name: install kustomize
    ansible.builtin.import_role:
      name: install_kustomize
    when: install_kustomize

  - name: install metallb
    ansible.builtin.import_role:
      name: install_metallb
    when: 
    - install_kustomize
    - install_metallb
    - disable_service_lb

