---
- hosts: k3s
  gather_facts: false
  tasks:
#  - name: install k3s
#    ansible.builtin.import_role:
#      name: install_k3s 
#
#  - name: install k3s
#    ansible.builtin.import_role:
#      name: install_rook
#    when: 
#    - install_rook
#
#  - name: install metallb
#    ansible.builtin.import_role:
#      name: install_metallb
#    when: 
#    - install_metallb
#    - disable_service_lb
#
#  - name: install awx
#    ansible.builtin.import_role:
#      name: install_awx
#    when: 
#    - install_awx
#
#  - name: install gitea
#    ansible.builtin.import_role:
#      name: install_gitea
#    when: 
#    - install_gitea
#
  - name: install docker distribution
    ansible.builtin.import_role:
      name: install_docker_distribution
    when: 
    - install_docker_distribution