---
- name: check shared filesystem exists
  ansible.builtin.shell:
    cmd: kubectl get po -n rook-ceph |grep rook-ceph-mds -c
  ignore_errors: true
  failed_when: false
  changed_when: false
  register: shared_filesystem_out

- name: create shared filesystem
  ansible.builtin.command:
    cmd: kubectl create -f filesystem-test.yaml
    chdir: /root/rook/deploy/examples
  when: "shared_filesystem_out.stdout | int == 0"
